### ISSUE TITLE
회원관리 API 개발

### ISSUE THREAD

**Issue by shindawull** [ccommit/fashion-commerce-server#3]
## 이슈내용
회원 정보 변경 기능을 구현한다.
- 비밀번호, 주소, 휴대폰 번호 변경

개발 일정 마감: 2023-08-13

**Comment by ccommit-dev** [comment]
예외처리는 어떻게 되는지 추가부탁드립니다.

**Comment by shindawull** [comment]
판매자 가입시 고려되야할 스키마, 비즈니스 로직 설명하기

**Comment by shindawull** [comment]
<details>
    <summary>예외처리에 대한 시퀀스를 말로 설명하여 추가하였습니다. </summary>

회원 정보 변경 요청 

1) 휴대폰 번호 변경

- 유효성 검사
    - 필수 값으로 휴대폰 번호란이 누락되어 있을 경우, 재입력 요청 response 전달한다.
    - 숫자 외의 문자열이나 다른 값이 들어갔는지 체크 → 숫자만 입력 요청 response 전달한다.
    - 패턴(규칙) 일치하는지 체크(자릿수)
    ex) 아래의 예시 패턴을 보여주며 재입력 요청 response 전달한다.
```
@Test
public void whenMatchesTenDigitsNumber_thenCorrect() {
    Pattern pattern = Pattern.compile("^\\d{10}$");
    Matcher matcher = pattern.matcher("2055550125");
    assertTrue(matcher.matches());
}
```


2) 주소 변경(우편번호 API 사용)

- 유효성 검사
    - 필수 값으로 주소 정보가 없을 경우, 재입력 요청 response 전달한다.
    - 글자 수 제한, 패턴(규칙) 일치 하는지 체크 후 재입력 요청 response 전달한다.
- API 연동 시, 연결 실패로 인하여 웹페이지를 열 수 없는 경우 → 재검색 요청 response 전달한다. ( 우편번호 API 의 예외코드 참고하여 예외처리 진행한다.)

3) 비밀번호 변경 (암호화로 재설정)

- 유효성 검사
    - 필수 값으로 비밀번호 정보가 누락되어 있을 경우, 재입력 요청 response 전달한다.
    - 비밀번호 패턴(규칙)에 알맞게 입력 했는지 체크해서 패턴에 알맞지 않을 경우 재입력 요청 response 전달한다.
    - 기존 비밀번호랑 동일하게 변경하면 중복된 비밀번호라는  response 전달한다.

4) 휴대폰번호, 주소, 비밀번호 변경 시 DB 저장 실패 → 예기치 못한 에러로 rollback 진행 후 완료 시 commit 후 실패에 대한 예외코드와 사유를 response 전달한다.

</details>

**Comment by shindawull** [comment]
판매자 가입 시, 회원 정보 테이블에서 관리자 여부 컬럼이 있습니다.
데이터 타입을 변경하여 일반, 판매자, 관리자 를 구분합니다. 

<details>
    <summary>판매자 비즈니스 로직 설명을 추가했습니다.</summary>

회원 정보 테이블에서 관리자여부 컬럼이 있는데 타입을 변경해서 일반, 판매자, 관리자 를 구분한다. 
→ 판매자인 경우 상품 등록/변경 가능하다. 
→(유효성검사) 판매자인 경우 상품을 등록한다./ 변경한다. 
→ 등록/변경 성공 시, 성공 response를 전달한다. 
→ 등록/변경 실패 시, 실패 response를 전달한다. 

</details>

**Comment by ccommit-dev** [comment]
> 2\. 주소 변경(우편번호 API 사용)

@shindawull 다울님 실제 연동할 우편 공공 api url 링크 댓글로 추가 부탁드립니다.

글자 수 제한, 패턴(규칙) 일치 하는지 체크 후 재입력 요청 response 전달한다.
-> 실제 regex를 작성해서 댓글로 추가 부탁드립니다~

비밀번호 변경 (암호화로 재설정)
-> 암호화 라이브러리를 어떤걸 사용하실지 링크 부탁드립니다.

**Comment by shindawull** [comment]
> 2\. 주소 변경(우편번호 API 사용)

**실제 연동할 우편번호 API URL 링크 추가하였습니다.**
-> https://postcode.map.daum.net/guide

**위의 우편번호 API URL의 제공되는 방법을 참고하여 실제 Regex를 추가 작성하였습니다.** 
1) 팝업을 이용하여 도로명 주소와 지번 주소 모두 보여주는 방식
-> 주소를 검색한 후, 사용자가 선택한 주소의 도로명 주소와 지번 주소가 그대로 입력창에 적용됩니다.

2) 우편번호와 주소필드에 사용자가 선택한 주소 값을 채워 넣는 방식
-> 하지만 사용자가 직접 입력하는 경우, 우편번호가 null 값, " "공백인 경우 체크하여 response 전달한다.
-> 우편번호 기본 5자리로, 5자리 제한하고 숫자만 입력 가능하다. 체크하여 부합하면 response 전달한다.
-> 외의 도로명주소, 지번주소, 상세주소, 참고사항은 입력한대로 진행한다. (체크사항 없음)

**Comment by shindawull** [comment]
> 2\. 주소 변경(우편번호 API 사용)

**실제 연동할 우편번호 API URL 링크 추가하였습니다.**
-> https://biz.epost.go.kr/ui/index.jsp 주소를 통해 key를 발급 받고 포스트맨으로 get url주소로 보내서 주소가 맞는지까지 확인. 

비밀번호 암호화 라이브러리 " Bcrypt 구현을 통한 패스워드 암호화" 사용한다.
